# Generated by Django 3.1.5 on 2021-01-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_status_pages_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='kill_local',
            field=models.BooleanField(default=False),
        ),
    ]
